external_components:
  - source: github://nic6911/esphome_components
    refresh: 0s  
  - source: github://epiclabs-uc/esphome@fix-885-old
    components: wifi 
    refresh: 0s
    
sentio:
    
select:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Set modbus mode"
    id: sentio_set_modbus_mode
    address: 0x00005
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Disabled" : 0
      "Read only" : 1
      "Read/Write" : 2
      "Write with password" : 3

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Sentio ferie mode"
    id: sentio_vacation_mode
    address: 27
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "OFF" : 0
      "ON" : 1
